version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"

python:
  install:
    - requirements: requirements-docs.txt
    - method: pip
      path: .

sphinx:
  builder: html
  configuration: docs/source/conf.py
